steps:
  - label: "CUDA, Julia v1.11"
    matrix:
      setup:
        version:
          - "1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      julia -e 'println("---- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.add(["CUDA", "Adapt", "KernelAbstractions"])'

      julia -e 'println("+++ :julia: Running CUDA GPU tests")
                include("SpeedyWeather/test/GPU/runtests.jl")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    # don't run GPU tests if 'skip-ci' or 'skip-gpu-ci' labels are present
    if: !contains(build.pull_request.labels.*.name, 'skip-ci')
    timeout_in_minutes: 30

  - label: "AMDGPU, Julia v1.11"
    matrix:
      setup:
        version:
          - "1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |

      julia -e 'println("---- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.add(["AMDGPU", "Adapt", "KernelAbstractions"])'

      julia -e 'println("+++ :julia: Running AMDGPU tests")
                include("SpeedyWeather/test/GPU/runtests.jl")'
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    # don't run GPU tests if 'skip-ci' or 'skip-gpu-ci' labels are present
    if: !contains(build.pull_request.labels.*.name, 'skip-ci')
    timeout_in_minutes: 30