name = "SpeedyInternals"
uuid = "34489162-d270-4603-8b96-37b04f830d73"
authors = ["SpeedyWeather contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
